title         : 'Columbia University Digital Humanities'
description   : 'The central informational portal for the varied digital humanities work at Columbia University'

url           : ''
baseurl: ''
permalink: ':title/'
source: 'src'

collections:
  projects:
    output: true
    permalink: /projects/:path.html
    title: projects
  people:
    output: true
    permalink: /people/:path.html
    title: people
  teams:
    output: true
    permalink: /teams/:path.html
    title: teams

sass:
    style: compressed


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


include: [_pages, '.htaccess']
exclude: [vendor, Gemfile*, Rakefile, README.md, LICENCE.md]
version: 0.8
